defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - learning_rate_logger
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val_acc/SSIM"
  mode: "max"
  save_last: True
  auto_insert_metric_name: False

early_stopping:
  monitor: "val_acc/SSIM"
  patience: 20
  mode: "max"

model_summary:
  max_depth: -1
